### ISSUE TITLE
Synology NAS

### ISSUE THREAD

**Issue by steven3333steven3333** [bpeters504/beersmith-docker#1]
Trying to load your docker image on my Synology NAS using the UI would you be willing to provide some assistance?
If so drop me a line at steven3333steven3333@gmail.com

**Comment by bpeters504** [comment]
Hey Steven, Sorry I just saw your message. Unfortunately I have no experience with a Synology NAS and this is my first experience with Docker. So I don't know how to help. I'll also email you because since I didn't get notified about your comment, I'm guessing you won't get notified about this comment.

**Comment by elecnix** [comment]
I wouldn't expect the NAS to allow running a container expecting an X server. If you run Linux, you could perhaps tweak the `$DISPLAY` variable to point to your desktop for a remote X connection, but then you could just run the container on your desktop.
